# https://doc.rust-lang.org/cargo/reference/config.html

[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32F439ZITx'

# Note: this fix issue where rust-analyzer wouldn't use the good toolchain
[unstable]
build-std = ["core"]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "trace"
